[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
gas_limit = 9223372036854775807
gas_price = 20000000000
optimizer = true
optimizer_runs = 1000000
via_ir = false
bytecode_hash = "none"
revert_strings = "default"
sparse_mode = false

# Compiler remappings for Uniswap V4
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/", 
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "forge-gas-snapshot/=lib/forge-gas-snapshot/src/",
    "solmate/=lib/solmate/src/"
]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"