
# alert_rules.yml
groups:
  - name: DexBrain
    rules:
      - alert: HighErrorRate
        expr: rate(api_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High API error rate
          description: Error rate is {{ $value }} per second

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High API latency
          description: 95th percentile latency is {{ $value }} seconds

      - alert: RateLimitExceeded
        expr: rate(rate_limit_exceeded_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High rate of rate limit exceeded
          description: {{ $value }} rate limit exceeded errors per second
