global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'meltedmindz1@gmail.com'
  smtp_auth_username: 'meltedmindz1@gmail.com'
  smtp_auth_password: 'Superman420!'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  - name: 'critical-alerts'
    email_configs:
      - to: 'meltedmindz1@gmail.com'
        subject: 'CRITICAL: DexBrain Alert - {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT
          
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          
          Labels:
          {{ range .Labels.SortedPairs }}  • {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Started: {{ .StartsAt }}
          {{ if .EndsAt }}Ended: {{ .EndsAt }}{{ end }}
          {{ end }}
          
          View in Grafana: http://157.90.230.148:3001
          View in Prometheus: http://157.90.230.148:9090

  - name: 'warning-alerts'
    email_configs:
      - to: 'meltedmindz1@gmail.com'
        subject: 'WARNING: DexBrain Alert - {{ .GroupLabels.alertname }}'
        body: |
          WARNING ALERT
          
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          
          Labels:
          {{ range .Labels.SortedPairs }}  • {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Started: {{ .StartsAt }}
          {{ if .EndsAt }}Ended: {{ .EndsAt }}{{ end }}
          {{ end }}
          
          View in Grafana: http://157.90.230.148:3001

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']