# docker-compose.yml for enhanced DexBrain
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DB_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/dexbrain
      - REDIS_URL=redis://redis:6379/0
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SECRET_KEY=${SECRET_KEY}
      - PROMETHEUS_PORT=9090
    depends_on:
      - db
      - redis
      - prometheus
    networks:
      - dexbrain-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=dexbrain
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dexbrain-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - dexbrain-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - dexbrain-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - dexbrain-network

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - dexbrain-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  dexbrain-network:
    driver: bridge