global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # DexBrain API Server
  - job_name: 'dexbrain-api'
    static_configs:
      - targets: ['157.90.230.148:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Dexter Frontend
  - job_name: 'dexter-frontend'
    static_configs:
      - targets: ['157.90.230.148:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 60s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['157.90.230.148:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['157.90.230.148:6379']
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['157.90.230.148:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Custom DexBrain Metrics
  - job_name: 'dexbrain-agents'
    static_configs:
      - targets: ['157.90.230.148:8081']
    metrics_path: '/agent-metrics'
    scrape_interval: 60s