global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dexter'
    static_configs:
      - targets: ['dexter:8000']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # - 'alertmanager:9093'

rules:
  - name: 'dexter_alerts'
    rules:
    - alert: HighMemoryUsage
      expr: process_resident_memory_bytes > 1e9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        
    - alert: HighErrorRate
      expr: rate(dexter_errors_total[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
