# Only deploy when manually triggered or on release tags
name: Deploy to Production

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
  
  # Or when a release tag is created
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      run: |
        echo "Deploying to ${{ github.event.inputs.environment || 'production' }}"
        # Add your deployment commands here
        # This only runs on manual trigger or version tags
        
    - name: Notify deployment
      run: |
        echo "✅ Deployment completed"